/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BookingBuilder.Booking;
import Managers.BookingManager;
import Managers.FlightManager;
import Flights.Airline;
import Flights.Flight;
import Interfaces.I_Booking;
import Interfaces.I_Flight;
import Interfaces.I_Membership;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Users.Customer;

/**
 *
 * @author Cailean
 */
public class CancelMenu extends javax.swing.JFrame {

    /**
     * Creates new form CancelMenu
     */
    private ArrayList<Booking> userBooking = new ArrayList<Booking>();
    private Customer cust;
    private DefaultTableModel model;
    public CancelMenu(Customer cust) throws Exception {
        initComponents();
        this.cust = cust;
        displayBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 300, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking", "User ID", "Flight Number", "Class", "Baggage", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableBooking);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Booked Flights");

        jButtonCancel.setText("Cancel Flight");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenu)
                    .addComponent(jButtonCancel))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        this.setVisible(false);
		UserMenu menu;
                
                
        try {
            menu = new UserMenu(cust);
            menu.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (jTableBooking.getSelectedRow() == -1) {
			JOptionPane optionPane = new JOptionPane("Please select one of the Flights you want to Cancel!",
					JOptionPane.ERROR_MESSAGE);
			JDialog dialog = optionPane.createDialog("Failure");
			dialog.setAlwaysOnTop(true);
			dialog.setVisible(true);

		} else if (jTableBooking.getSelectedRowCount() > 1) {
			JOptionPane optionPane = new JOptionPane("Please select only one Flight!", JOptionPane.ERROR_MESSAGE);
			JDialog dialog = optionPane.createDialog("Failure");
			dialog.setAlwaysOnTop(true);
			dialog.setVisible(true);

		} else {
			try {
				int selectedRow = jTableBooking.getSelectedRow();

				JOptionPane optionPane = new JOptionPane("Flight has been cancelled!", JOptionPane.OK_OPTION);
                                JDialog dialog = optionPane.createDialog("Flight Cancelled");
                                dialog.setAlwaysOnTop(true);
                                dialog.setVisible(true);
                                cancelFlight(selectedRow);
                                //displayBookings();

			} catch (Exception ex) {
				Logger.getLogger(FlightsList.class.getName()).log(Level.SEVERE, null, ex);
			}

		}
        
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void cancelFlight(int selectedFlight) throws Exception
    {
        Airline flight = this.userBooking.get(selectedFlight).getFlight();
        int bookingID = this.userBooking.get(selectedFlight).getBookingID();
        int flightNumber = flight.getFlight().getFlightID();
        this.cust.cancelFlightPoints(bookingID, cust.getUserID());
        I_Booking cancel = new BookingManager();
        Booking book = cancel.createBooking(bookingID, this.cust);
        cancel.cancelFlight(flightNumber, book);
        this.model.removeRow(selectedFlight);
        
        
    
    }
    private void displayBookings() throws Exception {

		model = (DefaultTableModel) jTableBooking.getModel();
                

		Object[] rowData = new Object[6];

		I_Booking bookManager = new BookingManager();

		this.userBooking = bookManager.getUserBookings(this.cust);

		userBooking.forEach(n -> {

			rowData[0] = n.getBookingID();
			rowData[1] = n.getCustomer().getUserID();
                        rowData[2] = n.getFlight().getFlight().getFlightID();
			rowData[3] = n.getClassType();
			rowData[4] = n.getBaggage();
			rowData[5] = n.getPrice();
			

			model.addRow(rowData);
		});

	}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBooking;
    // End of variables declaration//GEN-END:variables
}
