/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DB.CouponDBController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import Users.Customer;


public class CouponGenerator extends javax.swing.JFrame {

    private Customer user;
    public CouponGenerator(Customer user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jButton_generateCoupon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_coupon = new javax.swing.JTextField();
        jButton_mainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(570, 310, 0, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Enter the email you want to use your Coupon:");

        jButton_generateCoupon.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jButton_generateCoupon.setText("Generate Coupon");
        jButton_generateCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generateCouponActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Your Coupon:");

        jTextField_coupon.setEditable(false);
        jTextField_coupon.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N

        jButton_mainMenu.setText("Main Menu");
        jButton_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_generateCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_coupon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton_mainMenu)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton_generateCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_coupon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton_mainMenu)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_generateCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generateCouponActionPerformed
        // TODO add your handling code here:
        
        String targetEmail = jTextField_email.getText();
        String code =  "";
        CouponDBController couponGenerated = new CouponDBController();
        
        boolean emailExists = false;
        boolean generate = false;
        boolean canGenerate = false;
        try {
            emailExists = couponGenerated.emailCheck(targetEmail);
            canGenerate = couponGenerated.canGenerateAnotherCode(this.user.getUserID());
        } catch (Exception ex) {
            Logger.getLogger(CouponGenerator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if(targetEmail.equals("")){
            JOptionPane optionPane = new JOptionPane("The field is empty!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);

        }
        
        
         if(targetEmail.equals(this.user.getEmail())){
            JOptionPane optionPane = new JOptionPane("You Can't Enter Your Email!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            
            jTextField_email.setText("");
            jTextField_coupon.setText("");
            
        }
         

          if(!emailExists){
            JOptionPane optionPane = new JOptionPane("Email is not Registered in the System!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            
            jTextField_email.setText("");
            jTextField_coupon.setText("");
            generate = false;
        }
         if(!canGenerate){
             JOptionPane optionPane = new JOptionPane("You Already used the limited Coupons Generated!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            
            jButton_generateCoupon.setEnabled(false);
            jTextField_email.setText("");
         } 
          
          if(emailExists && !targetEmail.equals("") && !targetEmail.equals(this.user.getEmail()) && canGenerate){
             try {
                 code =  couponGenerated.generateOnClick(this.user.getUserID(), targetEmail);
                 jTextField_coupon.setText(code);
                 jButton_generateCoupon.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(CouponGenerator.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_jButton_generateCouponActionPerformed

    private void jButton_mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mainMenuActionPerformed
        this.dispose();
        UserMenu mainMenu = null;
        try {
            mainMenu = new UserMenu(this.user);
        } catch (Exception ex) {
            Logger.getLogger(CouponGenerator.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton_mainMenuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_generateCoupon;
    private javax.swing.JButton jButton_mainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField_coupon;
    private javax.swing.JTextField jTextField_email;
    // End of variables declaration//GEN-END:variables
}
