/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BookingBuilder.Booking;
import Managers.BookingManager;
import Managers.UserManager;
import Flights.Flight;
import Interfaces.I_Booking;
import Interfaces.I_Membership;
import Interfaces.I_User;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Users.Customer;
import Users.Manager;


/**
 *
 * @author Cailean
 */
public class EditUsers extends javax.swing.JFrame {

    /**
     * Creates new form EditUsers
     */
    private ArrayList<Customer> custList = new ArrayList<Customer>();
    private Manager man;
    private DefaultTableModel model;
    
    public EditUsers(Manager man) throws Exception {
        initComponents();
        this.man = man;
        displayUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUserList = new javax.swing.JTable();
        jButtonRemove = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "E-Mail", "First Name", "Last Name", "Gender", "DOB", "Contact", "Role"
            }
        ));
        jScrollPane2.setViewportView(jTableUserList);

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("User List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemove)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(356, 356, 356))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemove)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonCancel)
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
        ManagerMenu menu;
         try {
                    menu = new ManagerMenu(man);
                    menu.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
                
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        if (jTableUserList.getSelectedRow() == -1) {
			JOptionPane optionPane = new JOptionPane("Please select one of the Users you want to Delete!",
					JOptionPane.ERROR_MESSAGE);
			JDialog dialog = optionPane.createDialog("Failure");
			dialog.setAlwaysOnTop(true);
			dialog.setVisible(true);

		} else if (jTableUserList.getSelectedRowCount() > 1) {
			JOptionPane optionPane = new JOptionPane("Please select only one User!", JOptionPane.ERROR_MESSAGE);
			JDialog dialog = optionPane.createDialog("Failure");
			dialog.setAlwaysOnTop(true);
			dialog.setVisible(true);

		} else {
			try {
				int selectedRow = jTableUserList.getSelectedRow();

				JOptionPane optionPane = new JOptionPane("User has been Removed!", JOptionPane.OK_OPTION);
                                JDialog dialog = optionPane.createDialog("User Removed");
                                dialog.setAlwaysOnTop(true);
                                dialog.setVisible(true);
                                removeUser(selectedRow);
                                //displayBookings();

			} catch (Exception ex) {
				Logger.getLogger(EditUsers.class.getName()).log(Level.SEVERE, null, ex);
			}

		}
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void removeUser(int selectedFlight) throws Exception
    {
        int custID = this.custList.get(selectedFlight).getUserID();
        I_User user = new UserManager();
        user.removeUser(custID);
        this.model.removeRow(selectedFlight);
        
        
    
    }
    
    private void displayUsers() throws Exception {

		model = (DefaultTableModel) jTableUserList.getModel();
                

		Object[] rowData = new Object[8];

		I_User bookManager = new UserManager();
                custList = bookManager.getUserList();

		

		custList.forEach(n -> {

			rowData[0] = n.getUserID();
			rowData[1] = n.getEmail();
                        rowData[2] = n.getFirstName();
			rowData[3] = n.getLastName();
			rowData[4] = n.getGender();
			rowData[5] = n.getDateOfBirth();
                        rowData[6] = n.getDateOfBirth();
                        rowData[7] = n.getRole();
			

			model.addRow(rowData);
		});

	}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUserList;
    // End of variables declaration//GEN-END:variables
}
