package UI;

import DB.FlightDBController;
import Flights.Airline;
import Flights.Flight;
import Memento.CareTaker;
import Memento.Originator;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Users.Customer;

/**
 *
 * @author alialdobyan
 */
public class FlightsList extends javax.swing.JFrame {

    private Customer cust;
    private ArrayList<Airline> flightList;
    
    
    public FlightsList(Customer cust) throws Exception {
        initComponents();
         this.cust = cust;
        displayFlights();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Flights = new javax.swing.JTable();
        jButton_continue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));

        jTable_Flights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight number", "Arrival Time", "Arrival Date", "Arrival airport", "Departure Time", "Departure Date", "Departure Airport"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Flights.setLocation(new java.awt.Point(500, 300));
        jScrollPane1.setViewportView(jTable_Flights);

        jButton_continue.setText("Continue");
        jButton_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_continueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Select a flight to Book");

        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_continue)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_back)
                    .addComponent(jButton_continue))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_continueActionPerformed
        
        if(jTable_Flights.getSelectedRow() == -1){
            
            JOptionPane optionPane = new JOptionPane("Please select one of the Flights you want to Book!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }
        else if(jTable_Flights.getSelectedRowCount() > 1){
            JOptionPane optionPane = new JOptionPane("Please select only one Flight!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }
        else{
            try {
                int selectedRow = jTable_Flights.getSelectedRow();
              
                this.setVisible(false);
                
                Originator org = new Originator();
                CareTaker care = new CareTaker();
                org.setState("Initial State");
                org.setClassType("First Class");
                org.setBaggageQ(1);
                care.add(org.saveStateToMemento());
                
                BookingMenu flightBooking = new BookingMenu(cust, flightList, selectedRow, org,care);
                flightBooking.setVisible(true);
                
            } catch (Exception ex) {
                Logger.getLogger(FlightsList.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_jButton_continueActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        this.dispose();
        UserMenu mainMenu = null;
        try {
            mainMenu = new UserMenu(this.cust);
        } catch (Exception ex) {
            Logger.getLogger(FlightsList.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton_backActionPerformed
    
     private void displayFlights() throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTable_Flights.getModel();
        
        Object [] rowData = new Object[7];
        
        FlightDBController flightNumber = new FlightDBController();

         this.flightList = flightNumber.getFlightList();
         System.out.print(flightList.size());
         //String [] flights = new String[this.flightList.size()];

         for(int i = 0; i < flightList.size(); i++){  
             System.out.print(flightList.size());
             rowData[0] = flightList.get(i).getFlight().getFlightID(); 
             rowData[1] = flightList.get(i).getFlight().getArrivalTime();
             rowData[2] = flightList.get(i).getFlight().getArrivalDate();
             rowData[3] = flightList.get(i).getFlight().getArrivalAirport();
             rowData[4] = flightList.get(i).getFlight().getDepartureTime();
             rowData[5] = flightList.get(i).getFlight().getDepartureDate();
             rowData[6] = flightList.get(i).getFlight().getDepartureAirport();
             
             model.addRow(rowData);
         }

    }
     
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_continue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Flights;
    // End of variables declaration//GEN-END:variables

   
}
