package UI;

import Interfaces.I_User;
import Users.Customer;
import Managers.UserManager;

import java.util.logging.Level;
import java.util.logging.Logger;
import Users.Manager;

/**
 *
 * @author alialdobyan
 */
public class ManagerMenu extends javax.swing.JFrame {

	private Manager user;

	public ManagerMenu(Manager user) {
		initComponents();
		this.user = user;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton_editUsers = new javax.swing.JButton();
		jButton_viewSales = new javax.swing.JButton();
		jButton_ViewFlights = new javax.swing.JButton();
		jButton_Logout = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(570, 300));

		jButton_editUsers.setText("Edit Users");
		jButton_editUsers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_editUsersActionPerformed(evt);
				} catch (Exception ex) {
					Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});

		jButton_viewSales.setText("View Sales");
		jButton_viewSales.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_viewSalesActionPerformed(evt);
			}
		});

		jButton_ViewFlights.setText("View Flights");
		jButton_ViewFlights.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_ViewFlightsActionPerformed(evt);
			}
		});

		jButton_Logout.setText("Logout");
		jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_LogoutActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(95, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_ViewFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_viewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_editUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(93, 93, 93)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(45, 45, 45)
						.addComponent(jButton_editUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(49, 49, 49)
						.addComponent(jButton_viewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
						.addComponent(jButton_ViewFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(44, 44, 44).addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(50, 50, 50)));

		pack();
	}// </editor-fold>

	private void jButton_editUsersActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		this.setVisible(false);
                EditUsers menu;
                 try {
                    menu = new EditUsers(user);
                    menu.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
                
		
        
	}

	private void jButton_viewSalesActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
                SalesMenu menu;
                 try {
                    menu = new SalesMenu(user);
                    menu.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
                
	}

	private void jButton_ViewFlightsActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		I_User userManager = new UserManager();
		try {
			userManager.viewFlights();
		} catch (Exception ex) {
			Logger.getLogger(ManagerMenu.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {
		
                this.dispose();
                LoginMenu login = new LoginMenu();
		login.setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton jButton_editUsers;
	private javax.swing.JButton jButton_viewSales;
	private javax.swing.JButton jButton_Logout;
	private javax.swing.JButton jButton_ViewFlights;
	// End of variables declaration
}
